# Generated by Django 2.0.7 on 2018-07-15 18:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=20)),
                ('documentType', models.TextField(max_length=20)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.TextField(max_length=20)),
                ('company', models.CharField(max_length=20)),
                ('emailAddress', models.TextField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('province', models.TextField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('phone', models.TextField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
